/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.MeuPrimeiroProjetoJava;
// scaner é externo ao programa por isso precisa importar
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        
        int idade = leitor.nextInt();
        float cotacaoDolar = leitor.nextFloat();
        double cotacaoEuro = leitor.nextDouble();
        String nome = leitor.nextLine();
        String codigoRua = leitor.next();
        
        System.out.println("Texto que será exibido no console");
        System.out.print("Texto que será exibido no console");
    }
}
